apiVersion: 0.3.0
environments:
  default:
    destination:
      namespace: ks-dev
      server: https://192.168.99.108:8443
    k8sVersion: v1.13.4
    path: default
kind: ksonnet.io/app
libraries:
  incubator/redis:
    name: redis
    registry: incubator
    version: 2a6bd08597dde82a3d7eb7084585b3383ba6efe0
name: guestbook
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
version: 0.0.1
